#! /bin/bash
FLOW=`which flow`

echo ""
echo ""
echo ""
echo "WITHOUT passing in file paths (args are \`autocomplete --json ROW COL < FILE_CONTENTS\`):"
echo ""
echo "----"
echo "Checking for autocompletion at position 7,5 of bar.js. Should show option 'baz'."
echo "RESULT: `FLOW autocomplete --json 7 5 < bar_at_7_5.js`"
echo "----"
echo ""

echo ""
echo "----"
echo "Checking for autocompletion at position 9,6 of foo.js. Should show option 'fwump'."
echo "RESULT: `FLOW autocomplete --json 9 6 < foo_completing_whum_at_9_6.js`"
echo "----"
echo ""

echo ""
echo "----"
echo "Checking for autocompletion at position 9,5 of foo.js. This time accessing an attribute on the 'bar' object. Should show option 'baz'."
echo "RESULT: `FLOW autocomplete --json 9 5 < foo_completing_bar_at_9_5.js`"
echo "----"
echo ""


echo ""
echo ""
echo ""
echo "This time, WITH passing in file paths (args are \`autocomplete --json FILE_PATH ROW COL < FILE_CONTENTS\`):"
echo ""
echo "----"
echo "Checking for autocompletion at position 7,5 of bar.js. Should show option 'baz'."
echo "RESULT: `FLOW autocomplete --json ./bar_at_7_5.js 7 5 < bar_at_7_5.js`"
echo "----"
echo ""

echo ""
echo "----"
echo "Checking for autocompletion at position 9,6 of foo.js. Should show option 'fwump'."
echo "RESULT: `FLOW autocomplete --json ./foo_completing_whum_at_9_6.js 9 6 < foo_completing_whum_at_9_6.js`"
echo "----"
echo ""

echo ""
echo "----"
echo "Checking for autocompletion at position 9,5 of foo.js. This time accessing an attribute on the 'bar' object. Should show option 'baz'."
echo "RESULT: `FLOW autocomplete --json ./foo_completing_bar_at_9_5.js 9 5 < foo_completing_bar_at_9_5.js`"
echo "----"
echo ""
